import os
from dataclasses import dataclass
from typing import List

import jwt
from dotenv import load_dotenv

load_dotenv()

_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_PUBLIC_KEY_SECRET_ARN = os.environ.get("JWT_PUBLIC_KEY_SECRET_ARN")

if _PUBLIC_KEY_SECRET_ARN:
    # Lambda runtime: the RSA public key used to verify tokens issued by
    # lexi-users-ms is generated by Terraform and stored as a plain-text
    # PEM secret in AWS Secrets Manager (not JSON — SecretString IS the PEM).
    # Fetched once at import time (Lambda cold start) and cached for the
    # life of the execution environment.
    import boto3

    _secrets_client = boto3.client("secretsmanager")
    _PUBLIC_KEY = _secrets_client.get_secret_value(SecretId=_PUBLIC_KEY_SECRET_ARN)["SecretString"].encode("utf-8")
else:
    # Local/offline dev and tests: no AWS creds available (or desired), so
    # fall back to a PEM file on disk. Tests override `_PUBLIC_KEY` directly
    # via monkeypatch (see conftest.py's `patch_public_key` fixture) with a
    # disposable key pair they control, rather than relying on this file's
    # contents.
    _PUBLIC_KEY_PATH = os.environ.get("JWT_PUBLIC_KEY_PATH", os.path.join(_BASE_DIR, "keys", "public.pem"))
    with open(_PUBLIC_KEY_PATH, "rb") as _key_file:
        _PUBLIC_KEY = _key_file.read()


class InvalidTokenError(Exception):
    pass


@dataclass(frozen=True)
class AuthenticatedUser:
    user_id: str
    roles: List[str]


def verify_token(token: str) -> AuthenticatedUser:
    """Valida el JWT RS256 emitido por lexi-users-ms con su clave pública."""
    try:
        claims = jwt.decode(token, _PUBLIC_KEY, algorithms=["RS256"])
    except jwt.PyJWTError as exc:
        raise InvalidTokenError(str(exc)) from exc

    user_id = claims.get("userId")
    if not isinstance(user_id, str):
        raise InvalidTokenError("invalid userId claim")

    role_claim = claims.get("role") or ""
    roles = role_claim.split(",") if role_claim else []

    return AuthenticatedUser(user_id=user_id, roles=roles)
